### ISSUE TITLE
Specialising the module to non protein-protein interactions

### ISSUE THREAD

**Issue by jambo6** [scastlara/ppaxe#10]
I've had a play with this and its really nice. 

I'm somewhat unfamiliar with the NLP that goes into this (and NLP in general), but I wanted to know if this should be straightforward to extend to looking for interactions other than protein-protein.  

For example, I'm particular interested in looking for protein-disease interactions. If I have some list of proteins and diseases I am interested in finding interactions of, do you have any advice on how I can modify the ppaxe module to do this?

Thanks!

**Comment by scastlara** [comment]
Thanks for you comment!

Your request makes a lot of sense, but it wouldn't be as straightforward as it seems. If you wanted to adapt PPaxe you would need to:

1- Train a model to recognize diseases. For recognizing proteins, we trained the StanfordCoreNLP with some corpus (you can look up the article for the specific details). You would then need to plug it somewhere in the code to use it correctly. Here is here ppaxe is looking at the tags from StanfordCoreNLP: https://github.com/scastlara/ppaxe/blob/master/ppaxe/core.py#L566 you would need to modify it to retrieve your `disease` tags and annotate the words correctly.
2- Train a model to predict protein-disease associations. You would need a corpus for that, and then train a model. I guess a simple RandomForest like the one used by PPaxe would do the trick, although I am sure other models would be more appropriate. In any case, that would depend a lot on the quality (and quantity) of your data to begin with. Here is where the prediction happens: https://github.com/scastlara/ppaxe/blob/master/ppaxe/core.py#L1019 You would simply need to change the imported model.

Modifying ppaxe to do all of this sounds like a fun side-project, but probably not the best use of your (or my) time. If having fun coding it is not what appeals to you, and you are simply interested in the results, I suggest looking around in the scientific literature for something more specific. I am unaware of any up to date programs that do it, but I am sure many may do something similar. Something like this would be more appropriate for your request I think: https://www.sciencedirect.com/science/article/abs/pii/S0022283619301172 

Hope I could help you!

**Comment by jambo6** [comment]
Thanks a lot for this response. I see, that is tricker than anticipated. I was hoping the NLP model would be able to determine associations between a list of diseases and proteins without need for additional model training. 

I will try and look for something more ready to go, but perhaps I will come back at some point and give this modification a go if I cannot find anything more suited. 

Thanks again :)
