### ISSUE TITLE
where i put  the FINAL-ner-model.AImed+MedTag+BioInfer.ser.gz ？

### ISSUE THREAD

**Issue by xiongsircool** [scastlara/ppaxe#11]
i have down the FINAL-ner-model.AImed+MedTag+BioInfer.ser.gz, but i don't know how to use.
if can give me some idea, i'll appreciate

**Comment by scastlara** [comment]
Hey! You need to put it wherever you want, as long as it's later correctly set in the file ppaxe/data/server.properties.

This package is pretty old, so always recommended to use the Docker image. In the Dockerfile you will also find an example of how to make everything run.

Thanks for using this thing, if you have any problems just ask!

**Comment by xiongsircool** [comment]
I have resovler the problem,thank you. and i find the python3.7 is ok,but python 3.10 can't,because the sklearn can't use the version up 0.20.0.
thank you.NOW I have nomral use
